-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.my_contacts
(
    contact_id bigserial,
    last_name character varying,
    first_name character varying,
    phone numeric,
    email character varying,
    gender "char",
    birthday date,
    prof_id integer,
    postal_id integer,
    status_id integer,
    PRIMARY KEY (contact_id)
);

CREATE TABLE public.interests
(
    interest_id bigserial,
    interest character varying,
    PRIMARY KEY (interest_id)
);

CREATE TABLE public.my_contacts_interests
(
    my_contacts_contact_id bigserial,
    interests_interest_id bigserial
);

CREATE TABLE public.seeking
(
    seeking_id bigserial,
    seeking character varying,
    PRIMARY KEY (seeking_id)
);

CREATE TABLE public.seeking_my_contacts
(
    seeking_seeking_id bigserial,
    my_contacts_contact_id bigserial
);

CREATE TABLE public.profession
(
    prof_id serial,
    profession character varying,
    PRIMARY KEY (prof_id)
);

CREATE TABLE public.postal_code
(
    postal_id smallserial,
    province character varying,
    city character varying,
    suburb character varying,
    postal_code character varying,
    PRIMARY KEY (postal_id)
);

CREATE TABLE public.status
(
    status_id smallserial,
    status character varying,
    PRIMARY KEY (status_id)
);

ALTER TABLE public.my_contacts_interests
    ADD FOREIGN KEY (my_contacts_contact_id)
    REFERENCES public.my_contacts (contact_id)
    NOT VALID;


ALTER TABLE public.my_contacts_interests
    ADD FOREIGN KEY (interests_interest_id)
    REFERENCES public.interests (interest_id)
    NOT VALID;


ALTER TABLE public.seeking_my_contacts
    ADD FOREIGN KEY (seeking_seeking_id)
    REFERENCES public.seeking (seeking_id)
    NOT VALID;


ALTER TABLE public.seeking_my_contacts
    ADD FOREIGN KEY (my_contacts_contact_id)
    REFERENCES public.my_contacts (contact_id)
    NOT VALID;


ALTER TABLE public.my_contacts
    ADD FOREIGN KEY (postal_id)
    REFERENCES public.postal_code (postal_id)
    NOT VALID;


ALTER TABLE public.my_contacts
    ADD FOREIGN KEY (prof_id)
    REFERENCES public.profession (prof_id)
    NOT VALID;


ALTER TABLE public.my_contacts
    ADD FOREIGN KEY (status_id)
    REFERENCES public.status (status_id)
    NOT VALID;

END;

INSERT INTO interests(interest)
VALUES
	('Golf'),('Hiking'),('Coding'),('Bridge'),
	('Shopping'),('Running'),('Socialising'),('Gaming');
	
INSERT INTO seeking(seeking)
VALUES
	('Friendship'),('Mariage'),('Hook-up'),('Companion');

INSERT INTO status(status)
VALUES
	('Single'),('Divorced'),('It''s complicated');
	
INSERT INTO profession(profession)
VALUES
	('Accountant'),('Doctor'),('Lawyer'),('Programmer'),('Unemployed');
	
INSERT INTO profession(profession)
VALUES
	('Accountant'),('Doctor'),('Lawyer'),('Programmer'),('Unemployed');

INSERT INTO postal_code(province, city,suburb,postal_code)
VALUES
	('KZN','Durban', 'Westville', '3629'),
	('WC','Cape Town', 'Rondebosch', '7001'),
	('KZN','Durban', 'Kloof', '3610');
	
INSERT INTO my_contacts(first_name,last_name,phone,email,gender,birthday, prof_id,postal_id,status_id)
VALUES
	('Joe','Soap','0821234567','js@abc.com','Male','21 February 1990',1,1,1),
	('Jane','Doe','0786534250','jd@abc.com','Female','12 April 1992',2,1,1),
	('Bruce','Banner','0782345678','bb@abc.com','Male','21 June 1982',4,2,2);
	
INSERT INTO my_contacts_interests(my_contacts_contact_id,interests_interest_id)
VALUES
	(1,1),(1,3),(1,6),(1,8),
	(2,3),(2,5),(2,7),(2,8),
	(3,4),(3,6),(3,2),(3,5);
	
INSERT INTO seeking_my_contacts(my_contacts_contact_id,seeking_seeking_id)
VALUES
	(1,2),(1,4),
	(2,2),
	(3,1),(3,2),(3,3),(3,4);

SELECT  first_name, last_name, prof.profession, post.suburb, post.city, post.province, post.postal_code, status.status, int.interest, seeking.seeking
FROM my_contacts AS con
LEFT JOIN profession AS prof
ON con.prof_id = prof.prof_id
LEFT JOIN postal_code AS post
ON con.postal_id = post.postal_id
LEFT JOIN status
ON con.status_id = status.status_id
-- Left join many to many of my contacts to seeking
LEFT JOIN seeking_my_contacts AS seek_con
ON con.contact_id = seek_con.my_contacts_contact_id
LEFT JOIN seeking
ON seek_con.seeking_seeking_id = seeking.seeking_id
-- Left join many to many of my contacts to interests
LEFT JOIN my_contacts_interests AS int_con
ON con.contact_id = int_con.my_contacts_contact_id
LEFT JOIN interests AS int
ON int_con.interests_interest_id = int.interest_id
